### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by zbjornson** [natewatson999/js-gc#1]
Cool package! I don't think this works in Firefox anymore though. Looks like it attempted to use XPCOM?

Unfortunately there's no other way I know of to run FF's GC. `about:memory` uses `Components.utils.forceGC()` which isn't available in normal contexts.

**Comment by natewatson999** [comment]
I'm researching the issue, and hopefully will be able to fix it. If I can't get it working again in that environment, the code won't explicitly break anything. Instead, it'll just be pointless. 

Do you know which version of Firefox caused the script to no longer work? If I can't fix the bug, it'll at least be helpful for the documentation to clarify which versions of Firefox work and which ones don't.

**Comment by zbjornson** [comment]
Thanks -- no rush or pressure from me, more making a note.

I spot checked versions 35 through 57 and `window.QueryInterface` is undefined for all -- that's the intended mechanism for FF, right?

Safari is another one that I don't think exposes a way to run the GC.

**Comment by natewatson999** [comment]
I appreciate the bug report. Most of the stuff I publish on github isn't used very often, so it's nice to have an actual user.

Yes, window.QueryInterface is the intended one for the Firefox compatibles "the problematic ones". As of version 55, Components.interfaces.nsIDOMWindowUtils seems to no longer be defined, at least in standard client code and the dev console. The same is true for window.QueryInterface. I'm unfamiliar with Firefox extension development, so I will leave this in place, to avoid breaking anything. I'm pretty sure they're both based in XPCOM.

I've pretty much given up on Safari support.

**Comment by natewatson999** [comment]
I've updated the documentation to reflect the issue.
